### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by MaluNoPeleke** [Apacelus/chromeos-autofanctrl#1]
Maybe using https://github.com/supechicken/ChromeOS-AutoStart could help you with the Autostart feature!?

**Comment by apacelus** [comment]
I have tried using that, but unfortunately it wouldnt work, so I gave up. I also dont have a chromeos system anymore. Would you be willing to help?

**Comment by pazos** [comment]
Hi, the extension works fine. It also seem to work just fine even with more complex commands, like:

```
bash -c "while true; do
    if [ $(sudo ectool temps 0 | tail -n 1 | cut -d ' ' -f 14) -ge 45 ]; then
        sudo ectool autofanctrl
    else
        sudo ectool pwmsetfanrpm 0 0
        sudo ectool fanduty 0 0
    fi
    sleep 5
done"
```

That's probably not needed for most chromebooks, but mine acts weird with autofanctrl when temperatures are above 39 and below 45 (most of the time here when idle)

Anyhow, the behaviour described in this repo can be achieved with:

```
bash -c "while true; do sudo ectool autofanctrl; sleep 5; done"
``` 

Hope it helps, @MaluNoPeleke
